#! /bin/sh

# Copyright (c) 1998 Cygnus Solutions
# Written by Tom Tromey <tromey@cygnus.com>

# Choose the tests we want to run.
# Usage: choose [-verbose] output-directory [tag] ...
# If a tag starts with `java.' then it is considered to be a name in
# the hierarchy (e.g., `java.lang').  In this case only tests in that
# part of the hierarchy are selected.
# FIXME: provide more information on the meaning of the other tags.
# Note there is a special "not-a-test" tag which can be used
# to mark a file as not having any test information.
# Run in the source directory.

# FIXME: we assume `echo -n' won't print a newline.
# This is not portable.

verbose=
spectags=
tags=
files=
exclude_files=

if test "$1" = "-verbose"; then
   verbose=yes
   shift
fi

outdir="$1"
shift

# Some tags imply other tags.  For instance, JDK1.2 implies JDK1.1 and
# JDK1.0.  This makes it easier to keep the tags up to date in the
# source -- we only have to keep track of differences (as opposed to
# editing every source file when a new tag is added).  If we see an
# otherwise-unrecognized tag, and the file `mauve-TAG' exists, then we
# treat the contents of that file as a list of implied tags.
taglist=${1+"$@"}
seen_dashdash=
while test -n "$taglist"; do
   set $taglist
   i="$1"
   shift
   taglist=${1+"$@"}

   case "$i" in
    X--)
       seen_dashdash=yes
       ;;
    java.*)
       file="`echo $i | tr . /`"
       files="$files $file"
       ;;
    !java.*)
       file="`echo $i | tr . / | sed -e 's/!//'`"
       exclude_files="$exclude_files $file"
       ;;
    not-a-test)
       # You can't specify this.
       :
       ;;
    JDK1.2)
       tags="$tags JDK1.0 JDK1.1 $i"
       test -z "$seen_dashdash" && spectags="$spectags $i"
       ;;
    JDK1.1)
       tags="$tags JDK1.0 $i"
       test -z "$seen_dashdash" && spectags="$spectags $i"
       ;;
    *)
       if test -f "mauve-$i"; then
	  # We don't want tags from a file to be treated as specified
	  # on the command line.  So we add a `X--' before the
	  # expansion.  We don't use just `--' as this would confuse
	  # `set'.
	  taglist="$taglist X-- `sed -e 's/#.*$//g' mauve-$i`"
       fi
       tags="$tags $i"
       test -z "$seen_dashdash" && spectags="$spectags $i"
       ;;
   esac
done

test -n "$verbose" && echo "tags = $tags"
test -n "$verbose" && echo "spectags = $spectags"
test -n "$verbose" && echo "files = $files"
test -n "$verbose" && echo "exclude_files = $exclude_files"

choices=/tmp/choices-$$
echo -n "CHOICES = " > $choices
classes=/tmp/classes-$$
: > $classes

(cd gnu/testlet; find java -name '*.java' -print) |
while read file; do
   test -n "$verbose" && echo "Examining $file"
   if test -n "$files"; then
      ok=no
      for pat in $files; do
	 case $file in
	  ${pat}*)
	     ok=yes
	     break
	     ;;
	 esac
      done
   else
      ok=yes
   fi

   if test "$ok" = no; then
      test -n "$verbose" && echo " ... not in any file pattern"
      continue
   fi

   if test -n "$exclude_files"; then
      for pat in $exclude_files; do
	 case $file in
	  ${pat}*)
	     test -n "$verbose" && echo " ... excluded by pattern $pat"
	     ok=no
	     break
	     ;;
	 esac
      done
   fi
   if test "$ok" = no; then
      continue
   fi

   # Surround value with spaces so that case statements will work
   # correctly.
   taglist=" `grep '^// Tags:' gnu/testlet/$file | sed -e 's,^// Tags:,,'` "
   istest=yes
   case "$taglist" in
    *\ not-a-test\ *)
       istest=no
       ;;
   esac

   ok=no
   # If any tag on the tag list matches, then we are ok.
   for tag in $tags; do
      case "$taglist" in
       *" ${tag} "*)
          ok=yes
	  break
          ;;
      esac
   done

   # If any specified tag hits a `not' tag, then we are not ok.
   if test "$ok" = yes; then
      for tag in $spectags; do
	 case "$taglist" in
	  *" !${tag} "*)
	     ok=no
	     test -n "$verbose" && echo "File $file has tag !$tag"
	     break
	     ;;
	 esac
      done
   fi

   if test "$ok" = yes; then
      class="gnu.testlet.`echo $file | sed -e 's/\.java$//' | tr / .`"
      echo -n " gnu/testlet/$file" >> $choices
      if test "$istest" = yes; then
	 echo $class >> $classes
	 test -n "$verbose" && echo "Chose $class"
      fi
   fi
done

echo >> $choices

# Due to a weirdness in GNU make, we want to list the dependencies
# explicitly here.  This is really nasty.  But if we remove this, then
# SimpleTestHarness will never be built, because its dependencies
# won't include the .o files (but, strangely, the link line will).
sed -e 's/CHOICES =/SimpleTestHarness:/' \
   -e 's/\.java/.o/g' $choices > /tmp/x-$$
cat /tmp/x-$$ >> $choices
rm /tmp/x-$$

if test -f $outdir/choices \
   && cmp $choices $outdir/choices > /dev/null 2>&1; then
   # Files are the same.
   rm $choices $classes
else
   mv $choices $outdir/choices
   mv $classes $outdir/classes
fi

exit 0
